// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypeekfkhyfhbnrlwgjyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwZWVrZmtoeWZoYm5ybHdnanlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwOTc1MTAsImV4cCI6MjA2MzY3MzUxMH0.KQyHwU6OtkpLE9_Z24a4bwNoRfOjxTDo0q-zfKfap9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);